#!/bin/bash
for file in $(ls -1 .)
do
	if [[ "$file" =~ .sh$ ]]; then
		if [ "$(grep $file README.md)" == "" ]; then
			echo -e "\`\`\`shell\nwget -qO - https://raw.githubusercontent.com/korby/pasted-bin/master/$file | bash\n\`\`\`" >> README.md
		fi
	fi
done
git add README.md

exit 0
